# Generated by Django 3.2.5 on 2021-07-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
