# Generated by Django 3.2.5 on 2021-07-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_orden_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
