# Generated by Django 3.2.5 on 2021-07-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ingredientessandwich_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='tamaño_precio',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredientessandwich',
            name='precio',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
