# Generated by Django 3.2.5 on 2021-08-01 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210718_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
